# Generated by Django 4.2.7 on 2023-12-01 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade_list',
            name='國文',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AlterField(
            model_name='grade_list',
            name='數學',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AlterField(
            model_name='grade_list',
            name='理化',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AlterField(
            model_name='grade_list',
            name='英文',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
    ]
