# Generated by Django 4.2.7 on 2023-12-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_course_alter_grade_list_student_grade_list_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade_list',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
